name: Docker test and publish

on:
  repository_dispatch:
    branches:
      - GHActions-Test

jobs:
  build-and-publish:
    env:
      PUPPERWARE_ANALYTICS_STREAM: production
      IS_LATEST: true
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      VERSION: ${{ github.event.client_payload.version }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - run: gem install bundler
      - name: Build container
        working-directory: docker
        run: |
          echo "$VERSION"
          docker system prune --all --force --volumes
          docker builder prune --force --keep-storage=10GB
          make lint build test
      - name: Publish container
        working-directory: docker
        run: |
          docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
          make publish
      - name: Build release container
        env:
          IS_RELEASE: true
        working-directory: docker
        shell: bash {0}
        run: |
          make prep
          if [ $? -eq 0 ]; then
            make lint build test
          else
            echo "Skipping release container building and testing"
          fi
      - name: Publish release container
        env:
          IS_RELEASE: true
        working-directory: docker
        shell: bash {0}
        run: |
          make prep
          if [ $? -eq 0 ]; then
            make publish
          else
            echo "Skipping release container publishing"
          fi
